### ISSUE TITLE
Does it support React Native 0.62?

### ISSUE THREAD

**Issue by maphongba008** [blackberry/BlackBerry-Dynamics-React-Native-SDK#7]
Not really an issue, but I just want to know does this SDK supports React Native 0.62 or not. We're in 0.62, should we downgrade to 0.61 to use this SDK.

Thanks.

**Comment by volodymyrtaliar** [comment]
Hi @maphongba008,

This BlackBerry SDK for react Native v7 does not support 0.62 version of React Native.
You should downgrade to 0.61 to use BlackBerry SDK for react Native v7.

Best regards,
Volodymyr
